name: Build docker image
on: [workflow_dispatch]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v4
      - name: setup docker buildx
        id: buildx
        with:
          version: latest
        uses: docker/setup-buildx-action@v2
      - name: build multiarch (buildx) and push
        run: |
          docker buildx build \
          --push \
          --platform linux/arm64,linux/amd64 \
          --tag docker.tjausa.mooo.com/duckcross-api:latest \
          --tag docker.tjausa.mooo.com/duckcross-api:$(date +%Y%m%d%H%M) \
          .
