name: Build docker image
on: [workflow_dispatch]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v4
      - name: build
        run: docker build -t docker.tjausa.mooo.com/duckcross-api:latest .
      - name: push image to registry
        run: docker push docker.tjausa.mooo.com/duckcross-api:latest
